language: java
jdk:
- openjdk8
- openjdk11
- openjdk15
stages:
- test
- name: deploy
  if: type != pull_request
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2"
jobs:
  include:
  - stage: test
    script:
    - ./mvnw test -B -Dspring-boot.version=$SPRING_BOOT_VERSION
  - stage: deploy
    jdk: openjdk8
    env:
    - SPRING_BOOT_VERSION=1.5.22.RELEASE
    script:
    - chmod +x publish.sh
    - "./publish.sh"
env:
  matrix:
  - SPRING_BOOT_VERSION=1.5.22.RELEASE
  - SPRING_BOOT_VERSION=2.1.17.RELEASE
  - SPRING_BOOT_VERSION=2.2.10.RELEASE
  - SPRING_BOOT_VERSION=2.3.4.RELEASE
  global:
  - secure: dfgngaezAw1DvkwcgqBgouk3wyEvtUCjfZYlXQch5FfLSSt4bY4hbvLm3SA4Vf92wpcEzI12BjW/k8eQE2AGqd5GqVvOfwHqxCLesu/qp6OUNsbd3f7DNhXM8ND2HWkZStCIDR57qYTX1CxcmQeFwz72PHpfE+t275fjL/ZSwenvnA/8Yq7rJaydN1mtq2Akb6BS/bjCH/cr6+RU/WdyCPrj23P4oipVGpSl8DJgcCS7uTIFfNDDAAProWMYRISwvcP4qwWoJ+G3geWQjmXhGgypYsIJfITOO2wuYAWbiSTrv256NM6NGxhzrNp23EQEzjLqHMt8fV7GnTBDYEICalbLxl3/sHA1t4dEzQrvG8IjHzoTRHA6ZTpIG9u0Vctx7dv+c+nCLX9NCJ90I7/oFoeKJUtxMa53T1Ew/YsZGsL+95Nc9yTtz/yMMxZVIq+T8KBhZv/kI+KmS7mF536EWrzakmBseqCUKUvnilU04ycx0FM50MbTYGL/tFP/OUP0ueSfBebmmo1VxvRNwDAvoHY3Z+ad0VBhyZAVTCTvBOcde0B14yIW23GcKsG0B0VeVbfB7JuK0FhioLi7YDJ7f2zDbpUnBa715oN4c74UnQ/ft6fTabopFPyirsZg/F0Ty+LJ18BM3pgflZKiAwX+QMHKQl6z2CfpI4j+vz5USYU=
  - secure: m2uUMmNjzg7RC5dsxQHCtLJt3Ds3ORPRCZPpc8RAOAYlLVpYvmeUhdEsVERSwsnwvPZLDdhOJ5F9Tu3+/x6pWHRRvQLUalXxe8QiyMeG+5vVBU15HdbG/IsvImXncBWboxstyu/CJYFT2OhUQvQvfiFVOZJ/f0Dd/kO8ZOv24yFFQm9h7aMP8fNA9LHbdAjD/k6XGWiP9L6btadxvhSYFqw48sCaCoqvWwtnbSMFZnZ0pDQCSWKQVIcCcgfKSmCx510bszEHjDRQzv10b/o0PlKRDyrg4oixj9IixR18ZQAz5MfJziaS0w6n58nFBpLynxI70zB0ATKyOdijWprz8VCTnF9aFnZg43GKfwnsyo6oY1WQRBrhtHHSrTlAVrfy7vvO8eTJen3kf/ORsT8aO4lKM99D9iZlN3nNbygErkC0KWyLma7OYR86xhYv0dSmZqX+jVHY9DSgZVP5I767VPEMBdIg4zaIRj2TnTB8aFvdjPkpdPx2E31DEA6gGZ4oJrA9AJMwQ4NH7Vr7c0fE321iCuCEF+VVBFIK14eI1o6Vsryd67csLlrJFZ/+i+hqnWHw41i1UbeU+cYRkns/61D3evjdYY7Y9KcSEgs9MuNR5C0773eTS5DFwCW2A8bwrE2l4fVbZ4E6pxO2s2+mTlix/qYgqqvbN5A4mIw4iDY=
  - secure: WTm1iJD2j20S3kzOZ3ttMrq+/xIoMtJd3kuZYofSvA8RiyRidL+JOv1tVNKxCZEtY0OmlSXh8urOJ8L2IH60gLLRIaTglDdzOV7arujJ21sFo1UxBXar2O9M10iTRyDFl833zp01VrDP41QuXPGfPutMruRF38hBm5WE4IExC3/EEwuAxe0jNKXXxVyN7z93QK3zQunbewaN3EKXZyli9AXjPQyDKw0gY4lqfzVKMKyJyIGe5pN7T4hSRxS0Flke5WBgBP0QQSDbeOcCtLNAF+8fa+oZ3TkfZ/D2IUoGdZHNM8IHrvAqnsAxzmSbKAlo/InIPIjRBVvyavwi0elvHYzguoOzyDqyHquMODVtfNwtj9rW+Q2pA87txVECd98jrnbmJm4AqbYRYEuhH33etjWoYZt/FQ3A16+3gTXCVNHU1iFMCwIh/w95aHp1Q3hEEMtMo62INk1XdFbyWqqKxLFpQ/Yoh9XWtfP5/I+pXFui3J6dmXzURb/nTrbB39e00aKt6vdCUugBhImwttAxHCoNF+hUHRdmvXeDWzzkJAp9J8Rym3BGoCvTwurZl2zTn17464D2YHuacj7+955KcoQH2zmexhWHpWys6rAXTtWKFQq7AHK7SJlAg07rIrfsOzHV69zzcOkYXuSevmPJmRitkpNhnerQUrean9wkfik=
  - secure: myFvsfO7lcb9Zk4PkRKdj0D5O19xFh0bc0wUItgAYxNtQnBklq5d4DcqBqxQvrXBxzvF7gKDX7RtSk1RIceFZ6BNEj0xes8dE0tvf8lhzTa9kb+AYUOWe2fSAFlcHofbd7G0fxU5fOBLCX+gq8famcYWj3hpapl5yMpMocjp6kCvs/3PD4/CwFUSxWwi0KjlzxsN8vIntAIwOG42sMEwiyGMmAuEneIlHrABAAyoAToRk4gaP5t+xdkVjlPz4XpGX3euQMR/AgbpGWHuZuhgvBp1Jfr9ODex+pmPOSq1CS1HhJg9fzaOEpEnn+XHnhGyRUAnrKcP/A7Yix3ZcIR+W6mueMXXHxM3OY38bFP0Ar1W3G0P5hz2JnbQKY16EdMXvB2Gt/E6K2FRc6U1KO+eoLwqwGl3RVh70QhcBPJlQZDlj21aHprNu+v3Xc+CNmQTVTA454g5v6ZN1rPZTi2YnTdG4ZsFwyjpkNd1IqCOUausG4bgk8LrT1RuMeCl5nktSsKhycp6rsKi8h7eR6Cocuew507f6v2tnogukGR6EcB0nEbcl6zcZRVzbGVptHMkef8dzbnzTt/6RYyskQD6MTSGlIaIgFbgnZPGMYD+jXCAmDAkJApasdsUwqZKVqr4TcP1q99Qry5bXa92PRNjX8M3YHj+HQtYt21jfHBSVlo=
  - secure: V9P/0iKIsUQ25KjIEW2PoPKO4NMyuJlMJU3avbwWX5zma9BJlPbp14Mvwdn1MiTt2J43pDbVxAprcuhI3UmdxI02w+SPhZRXlXaB4Kn2AZS2zaqn37IVqwXVr5/NQunm4ULJAk9Ih55HRf/N9RdQQBBBCHq7Hc/SjRgGqsphqMJ+nGTbUIq8/u79W0bGFW08e6PRsdcf4utpiAahQAnrZeGW7PmkoSEF7iEQSLQ5yqH6EQrrEwH6kChAUsT2V3eJDg9vrI2Ohm3+LUz+GaJqWDzHCizu14Wry64psQipPoRhHwjLZTPNu4xo0An6lhH3ttun91Rs5dwV3fd/04NiSJzW59rpuA9J01q7I4lQao8Z9HZXFA98LigzDWf9rWeiP3Iwh/5HLdFLP2k+7nilVozrZljVZUFgA532Ty4NwT+SpvxAWviIu0HA7TVSgcQTPXyQf1q9NOUyuhq8KZQw9/QMt98WH5hmsppWtzPFzu3lX4UmKDatVA4dpeCTgIhgvHD6XYSV1qWrtgoYVL8L82O/YyNyJjjRuuzt3tsXoyBMAoVBcqDvSy0OH+9hjsAyg0WSE8hUe+hI2qnwRmAeKDUAILZDD6s3/hqmTMer/jtugtC2azLLKKVhP3C82Iltg5IPtWIffO1zKb8ABhvJhFdiBVFvGnpPyBFgzjsza3M=
  - secure: lW3Gw0q39k7WQSECjDFNHgmfvbrbfLtsdTdidG5sLkfh65iAKo26cvcNmRbpfx2ggoZTAtfDJTHV+v5BiImXJOgxg83UXd8I2Fb6ZRptsQNR1qXtfUATbVVV6gkOfVaAsCN1vhCZrwIYRVaCFzEVwIAdWQQJSQnFLNEzHAkXemjeWeA1za7r2Xi8g4amI8e73I8zbqFpDe9XjcD1P/n077Q6eWMR9+RvC0Kyk4ZqXA5oYUaoCplu4FuAYAw+Nw0B+SQxYZpTzi2SXBExDg2GKIAyS5NPSZKFkDtbKgpfPvFv5i1XA047PXXtbjMgRD4EUhlaLHIGE+ghDU1pi8j1Q//WB+TS2+iaiBIsuXL2QYqDSRmaM2gSnushhRO6Zemg/m++p5WZmRjlGgqLUUcji2+cXBOV6kf86vit+7D3CF7hhn5pNLOi55Qbul6K8HwiH0tZ+3ssF8GQzo71LycFm9cCkz/zEiK6OcAm3dp3aRQb/wYxXAytYEuOgjjKT/gatmLiROhMCc+QbqVj5CWJgD5jiG94xFyIofnUWm6Wg7VfccyL9dDSagYXu4zlkqUV8dyf8rajNGQ/5ghWEHE6Zg1T2zVtOgD19z6g/WEFVMdNKQ+qnL7hsr6HHObOThZHnPRnksUtdP7LHQWGQoE2eLG0FJey4ajf6TH8ZapRkuw=
