name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8
          cache: maven

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Test with Maven
        run: ./mvnw test -B

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: ./**/target/surefire-reports

  test-matrix:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [ test ]

    strategy:
      matrix:
        java: [ 11, 17 ]
        spring-boot-version: [ 2.3.12.RELEASE, 2.4.13, 2.5.14, 2.6.9, 2.7.1 ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Test with Maven
        run: ./mvnw -pl :doma-spring-boot-core,:doma-spring-boot-autoconfigure,:doma-spring-boot-starter test -B -Dspring-boot.version=${{ matrix.spring-boot-version }}

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: ./**/target/surefire-reports

  test-slf4j-backward-compatible:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [ test ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8
          cache: maven

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Test with Maven
        run: ./mvnw -B compile -Pbackward-compatible && ./mvnw -B test -Dmaven.main.skip=true -Ddoma.version=2.49.0

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: ./**/target/surefire-reports

  deploy:
    if: github.event_name == 'push' && contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest
    needs: [ test-matrix, test-slf4j-backward-compatible ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8
          cache: maven

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.SIGNING_KEY }}
          gpg_passphrase: ${{ secrets.SIGNING_PASSWORD }}
          nexus_username: ${{ secrets.OSSRH_USERNAME }}
          nexus_password: ${{ secrets.OSSRH_PASSWORD }}

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: ./**/target/surefire-reports
