name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        java: [ 8, 11, 17 ]
        spring-boot-version: [ 2.2.13.RELEASE, 2.3.12.RELEASE, 2.4.12, 2.5.6 ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Test with Maven
        run: ./mvnw test -B -Dspring-boot.version=${{ matrix.spring-boot-version }}

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: ./**/target/surefire-reports

  test-module:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 17
          cache: maven

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Copy module-info.java
        run: cp doma-spring-boot-core/src/module/java/module-info.java doma-spring-boot-core/src/main/java/ && cp doma-spring-boot-autoconfigure/src/module/java/module-info.java doma-spring-boot-autoconfigure/src/main/java/

      - name: Test with Maven
        run: ./mvnw test -B -pl doma-spring-boot-core,doma-spring-boot-autoconfigure -Dmaven.compiler.source=17 -Dmaven.compiler.target=17

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: ./**/target/surefire-reports

  deploy:
    if: github.event_name == 'push' && contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest
    needs: [ test, test-module ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 8
          cache: maven

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.SIGNING_KEY }}
          gpg_passphrase: ${{ secrets.SIGNING_PASSWORD }}
          nexus_username: ${{ secrets.OSSRH_USERNAME }}
          nexus_password: ${{ secrets.OSSRH_PASSWORD }}

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: ./**/target/surefire-reports
